import {MODULES,emptyDetails,validateDetails,mergeDetails} from './character.js';
import {characterReference} from './character-reference.js';
import {detailEditor,detailView,readDetails,statRow,itemRow} from './character-ui.js';
import {today,currentTime,recordKey,compareRecords,MAX_CAPTURES,weekOf,formatPower as fp,power,latest,weeklyDelta,recordsFor,validateRecord,validateState,mayEdit} from './domain.js';
import {getState,saveState,write,read,all,remove,commitRecord} from './store.js';
import {config} from './config.js';
import {DriveBackups} from './drive.js';
import {localBackup} from './backup.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3z',players:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M20 8v6m-3-3h6',rank:'M4 21V11h5v10m1 0V3h5v18m1 0v-7h5v7',upload:'M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6',calendar:'M4 5h16v16H4z M8 2v6m8-6v6M4 11h16',check:'m5 12 4 4L20 5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',compare:'M5 3v18M19 3v18M2 8h6m8 8h6M9 12h6',book:'M12 5C9 2 4 3 2 4v16c3-1 7-1 10 1 3-2 7-2 10-1V4c-2-1-7-2-10 1v16'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.home}"/></svg>`;
const isAdminPage=document.body.dataset.admin==='true';
let state, user=null, route=location.hash.slice(1)||'home', selected=new Set(), currentWeek=weekOf(today()), filter='', sort='power', draft=null, previewURLs=[],saveTimer,toastTimer;
const remote=!!config.apiBase;
let claim=null,claims=[],accounts=[];
const roleLabel=r=>({member:"Membre",officer:"Officier",admin:"Administrateur"}[r]||r);
let driveStatus={kind:'off',text:'Drive non connecté'},driveFiles=[];
const drive=new DriveBackups({clientId:config.googleClientId,snapshot:localBackup,
  remember:token=>{if(token)sessionStorage.setItem('alphabet-drive-token',JSON.stringify(token));else sessionStorage.removeItem('alphabet-drive-token');},
  status:(kind,text,last)=>{driveStatus={kind,text,last:last||driveStatus.last};for(const el of document.querySelectorAll('[data-drive-status]'))el.textContent=text;if(last)localStorage.setItem('alphabet-drive-last',JSON.stringify(last));if(kind==='ready'){drive.save().catch(()=>{});} }
});
function drivePanel(){return `<section class="panel spacer"><h2>Sauvegardes Google Drive</h2><p class="muted">Copie de cet appareil, captures comprises. Chaque sauvegarde crée une version datée distincte.</p><p data-drive-status role="status">${esc(driveStatus.text)}</p><div class="backup-actions">${button('Connecter Google Drive','drive-connect','primary')}${button('Sauvegarder maintenant','drive-save','quiet')}${button('Voir les sauvegardes','drive-list','quiet')}${button('Déconnecter Drive','drive-disconnect','quiet')}</div><p class="stat-caption spacer">Après connexion, sauvegarde automatique après les modifications, tant que cette page reste ouverte et que l’autorisation Google est valide. La synchronisation entre les membres reste à raccorder.</p></section>`;}
function driveChanged(){if(!remote)drive.changed();}

function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),6000);}
function dateLabel(date){return date?new Date(date+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'}):'Capture de référence';}
function recordLabel(r){return dateLabel(r.date)+(r.time?' à '+r.time:' · heure non renseignée');}
function powerFields(value='',unit='M'){return `<label class="field">Puissance<input name="power" type="text" required inputmode="decimal" autocomplete="off" placeholder="Ex. 30.49 ou 5,83" value="${esc(value)}"><small>Point ou virgule acceptés. Un suffixe saisi (M ou B) remplace l’unité choisie.</small></label><label class="field">Unité de puissance<select name="powerUnit">${[['M','M · millions'],['B','B · milliards'],['K','K · milliers'],['','Points (valeur entière)']].map(([v,label])=>`<option value="${v}" ${v===unit?'selected':''}>${label}</option>`).join('')}</select></label>`;}
function currentPlayer(){return state.players.find(p=>p.id===user?.playerId)||(remote?null:state.players[0]);}
function empty(title,text,action=''){return `<div class="empty">${icon('rank')}<strong>${title}</strong>${text}${action?`<p class="spacer">${action}</p>`:''}</div>`;}
function button(text,action,cls='',attrs=''){return `<button class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;}
function audit(action){state.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),actor:user?.name||'Atelier local',action});}
async function api(path,options={}){const response=await fetch(config.apiBase+path,{...options,signal:options.signal||AbortSignal.timeout(30000),headers:{'Content-Type':'application/json',...(sessionStorage.getItem('alphabet-session')?{Authorization:'Bearer '+sessionStorage.getItem('alphabet-session')}:{}),...options.headers}});const result=await response.json();if(!response.ok)throw new Error(result.error||'Service indisponible');return result;}
async function refresh(){const response=await api('/api/state');state=validateState(response.state);user=response.user;claim=response.claim||null;claims=response.claims||[];accounts=response.accounts||[];}
async function persist(message='Enregistré sur cet appareil'){if(remote)throw new Error('Cette action locale est désactivée en mode connecté.');await saveState(state);driveChanged();toast(message);}
function nav(){return [['home','home','Vue d’ensemble','Accueil'],['players','players','Joueurs','Joueurs'],['rank','rank','Classements','Rangs'],['import','upload','Mes captures','Captures'],['daily','check','Quotidien','Quotidien'],['events','calendar','Événements','Événements'],['compare','compare','Comparateur','Comparer'],['academy','book','Académie','Académie']].map(([id,ico,label,short],i)=>`<a class="${route===id&&!isAdminPage?'active':''} ${i>5?'desktop-nav':''}" href="${isAdminPage?'index.html':''}#${id}">${icon(ico)}<span class="nav-wide">${label}</span><span class="nav-short">${short}</span></a>`).join('');}
function shell(content){$('#app').innerHTML=`<div class="layout"><aside class="sidebar"><a class="brand" href="index.html"><img src="icon.svg" alt=""><div><strong>AlphaBet<span class="gold">.</span></strong><small>DUCK SURVIVAL</small></div></a><nav class="nav" aria-label="Navigation principale">${nav()}</nav><div class="sidebar-bottom"><a class="button quiet full" href="${isAdminPage?'index.html':'admin.html'}">${icon('settings')}${isAdminPage?'Retour au dashboard':'Administration'}</a><div class="guild-badge"><div class="monogram">AB</div><div><strong>Guilde AlphaBet</strong><br><small>${remote?'Espace membres':'Atelier local'}</small></div></div></div></aside><div class="workspace"><header class="topbar"><div class="desktop-crumb"><small>ALPHABET</small><span class="muted">/</span><span>${isAdminPage?'Administration':'Tableau de bord'}</span></div><div class="mobile-brand"><img src="icon.svg" alt=""><strong>AlphaBet<span class="gold">.</span></strong></div><div><span class="state-label">${remote?(user?'Connecté avec Discord':'Connexion requise'):'Données sur cet appareil'}</span>${button(user&&remote?esc(user.name):'Connexion Discord','account','quiet')}</div></header><main id="main" tabindex="-1">${!remote?'<div class="notice"><strong>Version locale</strong> · Tes essais restent sur cet appareil. La synchronisation entre membres reste à raccorder. Les copies Drive se configurent en bas de page.</div>':''}${membership()}${content}${!remote?drivePanel():''}<footer>AlphaBet · Duck Survival <span aria-hidden="true">/</span> ${remote?'Espace de guilde':'Atelier de préparation'} <a href="${isAdminPage?'index.html':'admin.html'}">${isAdminPage?'Dashboard':'Administration'}</a></footer></main></div></div>`;}
function membership(){
 if(!remote||!user||user.playerId)return '';
 const requested=state.players.find(p=>p.id===claim?.playerId);
 return `<section class="panel spacer"><h2>Associer ma fiche</h2><p>${claim?.status==='pending'?`Demande envoyée pour <strong>${esc(requested?.name||'ta fiche')}</strong>. Un responsable doit la valider avant tes premiers relevés.`:claim?.status==='rejected'?'Ta demande a été refusée. Vérifie ton pseudo et fais une nouvelle demande.':'Choisis ton pseudo dans le jeu. Un responsable vérifiera l’association avec ton compte Discord.'}</p><form id="claim-form"><label class="field">Mon pseudo dans le jeu<select name="playerId" required><option value="">Choisir ma fiche</option>${state.players.map(p=>`<option value="${esc(p.id)}" ${p.id===claim?.playerId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><button class="primary spacer" type="submit">${claim?.status==='pending'?'Corriger mon choix':'Demander l’association'}</button></form>${button('Vérifier ma validation','refresh-membership','quiet spacer')}<p class="stat-caption">Tes relevés seront enregistrés dans la base de la guilde après validation. Aucun compte Google n’est nécessaire.</p></section>`;
}
function registrations(){return remote&&['admin','officer'].includes(user?.role)?`<section class="panel spacer"><h2>Inscriptions à valider (${claims.length})</h2>${button('Actualiser','refresh-membership','quiet')}<p>Vérifie le compte Discord et le pseudo avant de valider.</p>${claims.map(c=>`<div class="connection"><div><strong>${esc(c.name)}</strong><p>Discord : ${esc(c.discordId)}<br>Fiche : ${esc(state.players.find(p=>p.id===c.playerId)?.name||c.playerId)}</p></div><div>${button('Valider','review-claim','primary',`data-id="${esc(c.discordId)}" data-request="${esc(c.requestId)}" data-decision="approved"`)} ${button('Refuser','review-claim','quiet',`data-id="${esc(c.discordId)}" data-request="${esc(c.requestId)}" data-decision="rejected"`)}</div></div>`).join('')||'<p>Aucune demande en attente.</p>'}${user?.role==='admin'?button('Importer les 50 fiches initiales','seed-roster','quiet spacer')+'<p class="stat-caption">L’import ajoute uniquement les fiches absentes ; les données existantes sont conservées.</p>':''}</section>`:'';}
function heading(kicker,title,desc,action=''){return `<div class="heading"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;}
function rosterNotice(){return state.guildSnapshot?'<div class="notice"><strong>Effectif prérempli depuis les captures : 50 / 51.</strong> Un membre reste à identifier. Les valeurs sont des références non datées ; elles ne comptent pas dans les statistiques hebdomadaires. Les grades du jeu ne donnent aucun droit dans l’application.</div>':'';}
function stats(){const dated=state.players.filter(p=>recordsFor(state,p.id).some(r=>weekOf(r.date)===currentWeek));const powers=state.players.map(p=>latest(state,p)?.power).filter(Number.isFinite);return `<div class="grid"><section class="panel"><div class="stat-label">Puissance des fiches renseignées</div><div class="stat-value gold">${powers.length?fp(powers.reduce((a,b)=>a+b,0)):'—'}</div><div class="stat-caption">${powers.length} fiche${powers.length>1?'s':''} avec une puissance · références incluses</div></section><section class="panel"><div class="stat-label">Joueurs enregistrés</div><div class="stat-value">${state.players.length.toString().padStart(2,'0')}</div><div class="stat-caption">Effectif actuel du dashboard</div></section><section class="panel"><div class="stat-label">Relevés cette semaine</div><div class="stat-value">${dated.length}<span class="muted"> / ${state.players.length}</span></div><div class="stat-caption">Semaine du ${dateLabel(currentWeek)}</div></section></div>`;}
function profileCard(p){if(!p)return empty('Aucune fiche','Ajoute le premier joueur dans l’administration.');const r=latest(state,p);return `<section class="panel profile-hero"><div class="profile-head"><div class="monogram">${esc(p.name.replace('AB_','').slice(0,2).toUpperCase())}</div><div><span class="eyebrow">${user?.playerId===p.id?'Ma fiche':'Fiche joueur'}</span><h2 style="margin:6px 0 0">${esc(p.name)}</h2></div></div><div class="stat-value">${fp(r?.power)}</div><div class="tags"><span class="tag">Niveau ${r?.level??'—'}</span><span class="tag">Aventure ${r?.adventure??'—'}</span><span class="tag">${r?.date?recordLabel(r):'Référence non datée'}</span></div>${p.rosterSnapshot?`<p class="stat-caption">Hall de guilde · ${esc(p.rosterSnapshot.gameRole||'Grade non relevé')} · Activité : ${p.rosterSnapshot.activity??'non visible'}${p.rosterSnapshot.nameNeedsReview?' · Orthographe du pseudo à confirmer':''}</p>`:''}<div class="profile-bottom"><small>${r?.date?'Dernier relevé validé':'Valeurs lues sur la capture d’origine'}</small>${button('Voir la progression','profile','quiet',`data-id="${esc(p.id)}"`)}</div></section>`;}
function home(){const p=currentPlayer();return heading('Le repaire de la guilde','Chaque canard compte.','La progression d’AlphaBet, semaine après semaine.',button(icon('upload')+'Importer mes captures','import','primary'))+rosterNotice()+stats()+`<div class="split">${profileCard(p)}<section class="panel"><div class="panel-head"><h2>Le prochain relevé</h2><span class="tag gold">Dimanche</span></div><p class="muted">Capture ton profil, vérifie ta puissance et garde une trace de ta progression.</p><div class="progress-line"><span style="width:${state.players.length?Math.round(state.players.filter(p=>recordsFor(state,p.id).some(r=>weekOf(r.date)===currentWeek)).length/state.players.length*100):0}%"></span></div><p class="stat-caption">Un relevé daté est nécessaire pour entrer dans les statistiques hebdomadaires.</p>${button('Préparer mon relevé','import','full primary')}<p class="stat-caption" style="margin-top:15px;margin-bottom:0">Les captures restent en brouillon jusqu’à ta validation.</p></section></div><div class="split"><section class="panel"><div class="panel-head"><h2>Classement de puissance</h2><a href="#rank">Tout voir</a></div>${playerTable(state.players.slice().sort((a,b)=>(latest(state,b)?.power||0)-(latest(state,a)?.power||0)).slice(0,5))}</section><section class="panel"><div class="panel-head"><h2>Au programme</h2><a href="#events">Événements</a></div>${eventList(true)}</section></div>`;}
function playerTable(players){if(!players.length)return empty('Aucun joueur trouvé','Essaie un autre nom.');return `<div class="table-wrap"><table><thead><tr><th>Rang</th><th>Joueur</th><th>Puissance</th><th>Évolution</th><th>Comparer</th></tr></thead><tbody>${players.map((p,i)=>{const r=latest(state,p),delta=weeklyDelta(state,p.id,currentWeek);return `<tr><td class="rank">${String(i+1).padStart(2,'0')}</td><td>${button(esc(p.name),'profile','name-btn',`data-id="${esc(p.id)}"`)}<br><small>${r?.date?recordLabel(r):r?'Référence non datée':'Sans relevé'}</small></td><td>${fp(r?.power)}</td><td class="${delta?.absolute>0?'green':''}">${delta?`${delta.absolute>0?'+':''}${delta.percent.toFixed(1).replace('.',',')} %`:'—'}</td><td><input type="checkbox" aria-label="Comparer ${esc(p.name)}" data-compare="${esc(p.id)}" ${selected.has(p.id)?'checked':''}></td></tr>`;}).join('')}</tbody></table></div>`;}
function players(){const list=state.players.filter(p=>p.name.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):(latest(state,b)?.[sort]||0)-(latest(state,a)?.[sort]||0));return heading('La force du collectif',route==='rank'?'Classements':'Les joueurs','Ouvre une fiche ou compare jusqu’à cinq membres.')+rosterNotice()+`<section class="panel"><div class="filterbar"><label class="field">Rechercher<input id="search" placeholder="Nom du joueur" value="${esc(filter)}"></label><label class="field">Trier par<select id="sort">${[['power','Puissance'],['level','Niveau'],['adventure','Aventure'],['name','Nom']].map(([v,l])=>`<option value="${v}" ${sort===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="field date-field">Semaine du<input type="date" id="week" value="${currentWeek}"></label>${button(`Comparer (${selected.size}/5)`,'compare','primary')}</div>${playerTable(list)}<p class="stat-caption spacer">Évolution : dernier relevé de la semaine choisie, comparé au dernier relevé antérieur. Une donnée manquante n’est jamais comptée comme zéro.</p></section>`;}
function chart(records){if(records.length<2)return empty('L’histoire commence ici','Deux relevés datés suffisent pour afficher une courbe.');const values=records.slice(-12);const min=Math.min(...values.map(r=>r.power)),max=Math.max(...values.map(r=>r.power)),span=max-min||max*.1||1;const points=values.map((r,i)=>`${45+i*510/(values.length-1)},${150-(r.power-min)/span*105}`);return `<svg class="chart" viewBox="0 0 600 205" role="img" aria-label="Progression de ${esc(fp(values[0].power))} à ${esc(fp(values.at(-1).power))}"><path d="M45 35V160H565" stroke="#434050" fill="none"/><polyline points="${points.join(' ')}" fill="none" stroke="#bb90fa" stroke-width="3"/>${points.map((p,i)=>`<circle cx="${p.split(',')[0]}" cy="${p.split(',')[1]}" r="4" fill="#efc879"><title>${recordLabel(values[i])} : ${fp(values[i].power)}</title></circle>`).join('')}<text x="45" y="190">${recordLabel(values[0])}</text><text x="555" y="190" text-anchor="end">${recordLabel(values.at(-1))}</text><text x="48" y="23">${fp(max)}</text></svg>`;}
function profile(id){const p=state.players.find(p=>p.id===id);if(!p)return empty('Joueur introuvable','Cette fiche n’est plus disponible.');const records=recordsFor(state,p.id);return heading('La progression dans le temps',esc(p.name),'Chaque relevé conserve sa date, son heure (Paris) et ses valeurs.',mayEdit(user,p.id)?button('Ajouter un relevé','import','primary',`data-player="${esc(p.id)}"`):'')+`<div class="split">${profileCard(p)}<section class="panel"><h2>Historique de puissance</h2>${chart(records)}</section></div><section class="panel spacer"><h2>Les relevés</h2>${records.length?`<div class="table-wrap"><table><thead><tr><th>Date et heure (Paris)</th><th>Puissance</th><th>Niveau</th><th>Aventure</th><th>Captures</th></tr></thead><tbody>${records.slice().reverse().map(r=>`<tr><td>${recordLabel(r)}</td><td>${fp(r.power)}</td><td>${r.level}</td><td>${r.adventure}</td><td>${button('Fiche','view-details','small',`data-id="${esc(r.id)}"`)} ${r.captureIds?.length?button(`${r.captureIds.length} capture(s)`,'view-captures','small',`data-id="${esc(r.id)}"`):'—'}</td></tr>`).join('')}</tbody></table></div>`:empty('Aucun relevé daté','La capture de référence n’entre pas dans le calcul des évolutions.')}</section>${characterPanel(p,records)}`;}
function compare(){const players=state.players.filter(p=>selected.has(p.id));return heading('Côte à côte','Comparer les joueurs','Jusqu’à cinq membres, sur les mêmes indicateurs.',button('Choisir les joueurs','players','quiet'))+(players.length?`<div class="compare-grid">${players.map(p=>{const r=latest(state,p),d=weeklyDelta(state,p.id,currentWeek);return `<section class="panel"><h3>${esc(p.name)}</h3><small>Puissance</small><div class="compare-number gold">${fp(r?.power)}</div><p>Niveau <strong>${r?.level??'—'}</strong></p><p>Aventure <strong>${r?.adventure??'—'}</strong></p><p class="muted">Évolution<br><strong>${d?(d.percent>0?'+':'')+d.percent.toFixed(1)+' %':'Pas assez de relevés'}</strong></p><small>${r?.date?recordLabel(r):'Référence non datée'}</small></section>`;}).join('')}</div>`:empty('À toi de choisir','Coche les joueurs dans le classement.',button('Voir les joueurs','players','primary')));}

function characterPanel(p,records){const r=records.at(-1);return `<section class="panel spacer" id="character-sheet"><div class="section-head"><h2>La fiche complète</h2>${r&&mayEdit(user,p.id)?button('Compléter / corriger la fiche','edit-details','primary',`data-id="${esc(r.id)}"`):''}</div><p class="muted">${r?'Relevé du '+recordLabel(r):'Aucun relevé détaillé daté.'}</p>${detailView(r?.details||emptyDetails())}${p.id==='psykokwak'?`<details class="reference-block"><summary>Captures d’origine retrouvées · référence non datée</summary><p>Lectures issues de tes captures. Les deux séries de statistiques sont conservées séparément : aucune date ni valeur manquante n’a été inventée. Ces références ne remplacent pas un relevé validé.</p>${detailView(characterReference)}</details>`:''}</section>`;}

function importPage(){const allowed=state.players.filter(p=>mayEdit(user,p.id));return heading('Du jeu au dashboard','Mes captures','Sélectionne tes captures, vérifie les chiffres, puis valide.')+(!allowed.length?empty('Profil à apparier','Connecte-toi à Discord. Un administrateur doit associer ton compte à ta fiche joueur.',button('Connexion Discord','account','primary')):`<section class="panel"><div class="notice">${remote?'Lis tes captures automatiquement, puis corrige les propositions avant validation.':'La lecture automatique nécessite le service Google connecté. Tu peux compléter toute la fiche manuellement ici.'}</div><form id="record-form" class="stack"><div class="form-grid"><label class="field">Joueur<select name="playerId" required>${allowed.map(p=>`<option value="${esc(p.id)}" ${draft?.playerId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label class="field">Date réelle du relevé<input name="date" type="date" required max="${today()}" value="${esc(draft?.date||today())}"></label><label class="field">Heure du relevé (Paris)<input name="time" type="time" required step="60" value="${esc(draft?.time||currentTime())}"></label></div><div class="upload-zone">${icon('upload')}<h2>Ajoute les captures de ton téléphone</h2><p class="muted">PNG, JPEG ou WebP · jusqu’à ${MAX_CAPTURES} captures de 8 Mo chacune</p><input id="captures" type="file" accept="image/png,image/jpeg,image/webp" multiple aria-label="Importer des captures d’écran"><small>Le brouillon et ses images sont conservés sur cet appareil.</small></div><div class="capture-grid" id="capture-preview"></div>${remote?'<button type="button" class="quiet" data-action="analyze-captures">Lire mes captures automatiquement</button><p class="muted">Analyse des images par Google. Les résultats restent un brouillon à vérifier ; cette action utilise le service de lecture configuré par la guilde.</p>':''}<p id="analysis-status" class="analysis-progress" role="status">${esc((draft?.analysisMessages||[]).join("\n"))}</p><div class="form-grid">${powerFields(draft?.power||'',draft?.powerUnit??(draft?.power?'':'M'))}<label class="field">Niveau<input name="level" required type="number" min="0" max="1000000" step="1" value="${esc(draft?.level??'')}"></label><label class="field">Aventure<input name="adventure" required type="number" min="0" max="1000000" step="1" value="${esc(draft?.adventure??'')}"></label></div>${detailEditor(draft?.details||emptyDetails())}<small id="draft-status" role="status">${draft?'Brouillon récupéré.':'Les modifications du formulaire sont sauvegardées automatiquement.'}</small><label class="check-row"><input type="checkbox" name="verified" required><span>J’ai vérifié le joueur, la date et les valeurs.</span></label><button class="primary full" type="submit">Valider le relevé</button><button type="button" class="quiet" data-action="discard-draft">Abandonner ce brouillon</button></form></section>`);}
function daily(){const p=currentPlayer();return heading('Un jour à la fois','Les modes quotidiens','Un suivi personnel, remis à zéro à chaque nouvelle date.')+`<section class="panel"><div class="panel-head"><h2>${dateLabel(today())}</h2><span class="tag">${esc(p?.name||'Aucune fiche')}</span></div>${state.modes.length?state.modes.map(m=>`<label class="check-row"><input type="checkbox" data-mode="${esc(m.id)}" ${state.daily.some(d=>d.playerId===p?.id&&d.modeId===m.id&&d.date===today()&&d.done)?'checked':''} ${!mayEdit(user,p?.id)?'disabled':''}><span>${esc(m.name)}</span></label>`).join(''):empty('Les modes restent à définir','Les captures détaillées des modes quotidiens ne figurent pas dans les échanges récupérés. L’administration permet d’ajouter leurs noms exacts.')}<p class="stat-caption spacer">Les coches sont déclaratives. Elles ne prouvent pas une activité dans le jeu.</p></section>`;}
function eventList(compact=false){const events=state.events.slice().sort((a,b)=>a.date.localeCompare(b.date)).filter(e=>!compact||e.date>=today());return events.length?events.slice(0,compact?2:100).map(e=>`<article class="event"><time>${dateLabel(e.date)}</time><h3 style="margin:9px 0">${esc(e.title)}</h3><p class="muted">${esc(e.description)}</p></article>`).join(''):empty('Rien au calendrier','Les prochains événements de guilde apparaîtront ici.');}
function events(){return heading('Les rendez-vous de la guilde','Événements','Dates, objectifs et consignes au même endroit.')+`<section class="panel">${eventList()}</section>`;}
function academy(){return heading('Apprendre ensemble','Académie & AlphaBot','Les prochains outils d’AlphaBet.')+`<section class="panel">${empty('Contenu à préparer','Les guides et l’analyse intelligente ont été prévus dans le cadrage. Ils attendent les règles et les captures des 12 modules ; aucun conseil de jeu n’est inventé.')}</section>`;}
function accountPanel(){
 if(!remote)return '<section class="panel spacer"><h2>Comptes et permissions</h2><p>La gestion des comptes Discord est disponible sur le site connecté.</p></section>';
 if(user?.role!=='admin')return '';
 return `<section class="panel spacer"><div class="panel-head"><h2>Comptes et permissions</h2>${button('Actualiser','refresh-membership','quiet')}</div><p>Les officiers peuvent valider les inscriptions et gérer les fiches, relevés, modes et événements. Seuls les administrateurs peuvent changer les rôles ou désactiver un compte.</p><p class="muted">Les membres apparaissent ici après leur première connexion Discord. Ton compte principal est protégé.</p>${accounts.map(a=>`<div class="connection"><div><strong>${esc(a.name)}</strong> <span class="tag">${esc(roleLabel(a.role))}</span>${a.disabled?' <span class="tag">Désactivé</span>':''}<p>${esc(state.players.find(p=>p.id===a.playerId)?.name||'Sans fiche associée')} · Discord ${esc(a.id)}</p></div>${a.protected?'<span class="muted">Compte protégé</span>':button('Gérer les droits','edit-account','quiet',`data-id="${esc(a.id)}"`)}</div>`).join('')||'<p>Aucun compte disponible. Actualise après la mise à jour du serveur.</p>'}${button('Apparier un compte Discord','pair','quiet spacer')}</section>`;
}
function managementList(kind,items){return `<div class="stack spacer">${items.map(item=>`<div class="connection"><div><strong>${esc(item.name||item.title)}</strong>${item.date?`<p>${dateLabel(item.date)}</p>`:''}</div>${button('Modifier','edit-'+kind,'quiet',`data-id="${esc(item.id)}"`)}</div>`).join('')||'<p class="muted">Aucun élément.</p>'}</div>`;}
function recordManagement(){return `<section class="panel spacer"><h2>Corriger un relevé</h2><p>Corrige les chiffres en conservant le joueur, la date et les captures. Le motif et les anciennes valeurs sont consignés dans l’historique.</p>${state.records.length?`<label class="field">Relevé<select id="admin-record">${[...state.records].sort((a,b)=>compareRecords(b,a)).map(r=>`<option value="${esc(r.id)}">${esc(state.players.find(p=>p.id===r.playerId)?.name)} · ${recordLabel(r)} · ${fp(r.power)}</option>`).join('')}</select></label>${button('Corriger les valeurs','edit-record','quiet spacer')}`:'<p class="muted">Aucun relevé daté pour le moment.</p>'}</section>`;}
function admin(){
 if(remote&&!['admin','officer'].includes(user?.role))return heading('Espace réservé','Administration','Les permissions sont vérifiées par le serveur.')+empty('Accès non autorisé','Connecte-toi avec un compte habilité.',button('Connexion Discord','account','primary'));
 return heading('Le poste de commande','Administration','Gère les membres, les accès et les activités de la guilde.')+(!remote?'<div class="notice">Atelier local : les modifications restent sur cet appareil.</div>':'')+accountPanel()+registrations()+recordManagement()+`<div class="grid spacer"><section class="panel"><h2>Membres (${state.players.length})</h2>${button('Ajouter un joueur','add-player','primary')}${managementList('player',state.players)}</section><section class="panel"><h2>Modes quotidiens</h2>${button('Ajouter un mode','add-mode','quiet')}${managementList('mode',state.modes)}</section><section class="panel"><h2>Événements</h2>${button('Créer un événement','add-event','quiet')}${managementList('event',state.events)}</section></div><div class="split"><section class="panel"><h2>Sauvegardes et données</h2><p>${remote?'Les données de la guilde sont enregistrées dans Google. La programmation des sauvegardes se gère dans la console Google Cloud.':'Les données de cet atelier sont conservées sur cet appareil.'}</p><div class="backup-actions">${button(remote?'Exporter les statistiques':'Exporter la sauvegarde','export','quiet')}${!remote?button('Restaurer une sauvegarde','restore','quiet'):''}</div><p class="stat-caption">${remote?'Cet export contient les statistiques, sans les fichiers des captures.':'La sauvegarde locale inclut les captures.'}</p></section><section class="panel"><h2>Historique des modifications</h2>${state.audit.length?`<div class="timeline">${state.audit.slice(0,20).map(a=>`<div class="timeline-item"><small>${esc(new Date(a.at).toLocaleString('fr-FR'))} · ${esc(a.actor)}</small><p>${esc(a.action)}</p></div>`).join('')}</div>`:empty('Aucune modification','Les validations et changements seront consignés ici.')}</section></div>`;
}
async function render(){previewURLs.forEach(URL.revokeObjectURL);previewURLs=[];shell(remote&&!user?heading('Bienvenue chez AlphaBet','Ton espace de guilde','Connecte-toi avec Discord pour retrouver ta fiche et tes relevés.',button('Se connecter avec Discord','account','primary')):isAdminPage?admin():route.startsWith('player/')?profile(decodeURIComponent(route.slice(7))):({home,players,rank:players,compare,import:importPage,daily,events,academy}[route]||home)());if(route==='import'&&!isAdminPage&&draft)await previews();}
async function previews(){const target=$('#capture-preview');if(!target)return;previewURLs.forEach(URL.revokeObjectURL);previewURLs=[];target.innerHTML='';for(const id of draft?.captureIds||[]){const capture=await read('captures',id);if(!capture)continue;const url=URL.createObjectURL(capture.blob);previewURLs.push(url);target.insertAdjacentHTML('beforeend',`<figure><img loading="lazy" src="${url}" alt="${esc(capture.name)}"><figcaption>${esc(capture.name)}</figcaption></figure>`);}}
function go(next){if(isAdminPage)location.href='index.html#'+next;else if(location.hash.slice(1)===next)render();else location.hash=next;}
function dialog(title,body){$('#dialog').innerHTML=button('Fermer','close','close quiet')+`<h2>${title}</h2>${body}`;$('#dialog').showModal();}
function formDialog(title,fields,handler){dialog(title,`<form id="modal-form" class="stack">${fields}<button class="primary" type="submit">Enregistrer</button></form>`);$('#modal-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{await handler(Object.fromEntries(new FormData(e.target)));$('#dialog').close();await render();}catch(error){toast(error.message);}finally{b.disabled=false;}};}
function input(label,name,type='text',extra=''){return `<label class="field">${label}<input name="${name}" type="${type}" required ${extra}></label>`;}
async function saveDraft(){const form=$('#record-form');if(!form)return;const values=Object.fromEntries(new FormData(form));draft={...draft,id:draft?.id||crypto.randomUUID(),...values,captureIds:draft?.captureIds||[],details:readDetails(form,{validate:false})};delete draft.verified;await write('drafts',draft);driveChanged();if($('#draft-status'))$('#draft-status').textContent='Brouillon enregistré sur cet appareil.';}
async function login(){if(!remote){dialog('Connexion Discord',`<p>Le site est encore en préparation locale. La connexion sera disponible après configuration de l’application Discord et du service Google.</p><p class="muted">Le profil actuellement affiché est une fiche de référence, pas une session Discord.</p>`);return;}if(user){dialog('Ton compte',`<p>${esc(user.name)} · ${esc(roleLabel(user.role))}</p><p>${user.playerId?'Profil apparié':'Appariement par un administrateur nécessaire'}</p>${button('Se déconnecter','logout')}`);return;}const verifier=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(hash))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');sessionStorage.setItem('alphabet-verifier',verifier);const {url}=await api('/auth/start',{method:'POST',body:JSON.stringify({challenge})});location.assign(url);}
async function adminMutation(action,data){if(remote){await api('/api/admin',{method:'POST',body:JSON.stringify({action,...data})});await refresh();toast('Enregistré dans Google');}else{if(action.startsWith('edit-')){const key={player:'players',mode:'modes',event:'events',record:'records'}[action.slice(5)],item=state[key]?.find(x=>x.id===data.id);if(!item)throw new Error('Élément inconnu');if(action==='edit-record'){audit('Correction du relevé '+item.date+' : '+data.reason+' ; anciennes valeurs '+JSON.stringify({power:item.power,level:item.level,adventure:item.adventure}));Object.assign(item,{power:data.power,level:data.level,adventure:data.adventure});}else{Object.assign(item,data);audit('Modification : '+(data.name||data.title));}await persist();return;}if(action==='player')state.players.push({id:crypto.randomUUID(),name:data.name.trim()});if(action==='mode')state.modes.push({id:crypto.randomUUID(),name:data.name.trim()});if(action==='event')state.events.push({id:crypto.randomUUID(),...data});audit(action==='player'?'Joueur ajouté : '+data.name:action==='mode'?'Mode ajouté : '+data.name:'Événement créé : '+data.title);await persist();}}
let analysisRunning=false;
async function uploadDraftCapture(id){const c=await read('captures',id);if(!c)throw new Error('Capture locale manquante.');const data=await new Promise((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=()=>no(new Error('Image illisible'));fr.readAsDataURL(c.blob);});return api('/api/captures',{method:'POST',body:JSON.stringify({id,playerId:draft.playerId,name:c.name,data})});}
async function analyzeCaptures(button){
 if(analysisRunning)return;clearTimeout(saveTimer);await saveDraft();if(!draft.captureIds.length)throw new Error('Ajoute au moins une capture.');
 // Validate before calling a paid service. Incomplete manual rows must be completed or removed.
 validateDetails(draft.details||emptyDetails());
 if(draft.analysisVersion!==2){draft.analyzed=[];draft.analysisMessages=[];draft.analysisVersion=2;}
 analysisRunning=true;button.disabled=true;const form=$('#record-form'),controls=[...form.querySelectorAll('input,select,textarea,button')],previous=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);
 const draftId=draft.id,playerId=draft.playerId;let done=0;const messages=[...(draft.analysisMessages||[])];
 try{for(const id of draft.captureIds){if(!$('#record-form')||draft?.id!==draftId)throw new Error('Lecture interrompue ; les résultats déjà lus sont conservés.');if(draft.analysisVersion===2&&(draft.analyzed||[]).includes(id)){done++;continue;}
 const status=$('#analysis-status');if(status)status.textContent=`Lecture ${done+1}/${draft.captureIds.length}…`;
 const uploaded=await uploadDraftCapture(id),r=await api('/api/recognize',{method:'POST',signal:AbortSignal.timeout(100000),body:JSON.stringify({captureId:uploaded.id})});
 if(draft?.id!==draftId||draft.playerId!==playerId)throw new Error('Le brouillon a changé ; résultat non appliqué.');
 const expected=state.players.find(p=>p.id===playerId)?.name||'',normalize=n=>n.toLowerCase().replace(/[^a-z0-9]/g,'');
 if(r.playerName&&normalize(r.playerName)!==normalize(expected)){messages.push(`Capture ignorée : pseudo ${r.playerName}, fiche ${expected}.`);continue;}
 draft.details=mergeDetails(draft.details,r.details);
 for(const k of ['power','level','adventure'])if(r[k]){if(!draft[k]){draft[k]=r[k];if(k==='power')draft.powerUnit='';}else if(String(draft[k])!==r[k])messages.push(`${k} : la capture propose ${r[k]} ; la saisie ${draft[k]} est conservée.`);}
 messages.push(...(r.warnings||[]));draft.analyzed=[...(draft.analyzed||[]),id];draft.analysisMessages=messages.slice(-100);await write('drafts',draft);done++;}
 }catch(e){messages.push(e.message);}finally{analysisRunning=false;controls.forEach((c,i)=>c.disabled=previous[i]);button.disabled=false;if(draft?.id===draftId){await render();const status=$('#analysis-status');if(status)status.textContent=`${done}/${draft.captureIds.length} capture(s) traitée(s). Vérifie toutes les propositions avant validation.\n`+messages.join('\n');}}
}
async function exportBackup(){const captures=remote?[]:await all('captures');const output={schema:1,kind:remote?'statistics-export':'local-backup',exportedAt:new Date().toISOString(),state,captures:await Promise.all(captures.map(async c=>({...c,blob:undefined,data:await new Promise((ok,no)=>{const reader=new FileReader();reader.onload=()=>ok(reader.result);reader.onerror=()=>no(reader.error);reader.readAsDataURL(c.blob);})}))),drafts:remote?[]:await all('drafts')};const blob=new Blob([JSON.stringify(output)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`alphabet-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Sauvegarde exportée.');}
async function restoreFile(file){if(file.size>120*1024*1024)throw new Error('Sauvegarde trop volumineuse (120 Mo maximum).');const backup=JSON.parse(await file.text());if(backup.kind==='statistics-export'||backup.kind==='server-backup')throw new Error('Ce fichier est un export serveur, pas une sauvegarde locale.');validateState(backup.state);if(!Array.isArray(backup.captures)||!Array.isArray(backup.drafts))throw new Error('Captures ou brouillons manquants.');const captures=backup.captures.map(c=>{if(typeof c.id!=='string'||typeof c.name!=='string'||!/^data:image\/(png|jpeg|webp);base64,/.test(c.data))throw new Error('Capture invalide.');const bytes=atob(c.data.split(',')[1]);return {id:c.id,name:c.name,blob:new Blob([Uint8Array.from(bytes,c=>c.charCodeAt(0))],{type:c.data.slice(5,c.data.indexOf(';'))})};});const ids=new Set(captures.map(c=>c.id));if(backup.state.records.some(r=>(r.captureIds||[]).some(id=>!ids.has(id))))throw new Error('Il manque des captures dans cette sauvegarde.');for(const d of backup.drafts)if(typeof d.id!=='string'||!Array.isArray(d.captureIds)||d.captureIds.some(id=>!ids.has(id)))throw new Error('Brouillon invalide.');dialog('Restaurer cette sauvegarde ?',`<p>${backup.state.players.length} joueur(s), ${backup.state.records.length} relevé(s), ${captures.length} capture(s).</p><p>Les données locales actuelles seront remplacées. Exporte-les d’abord si tu veux les conserver.</p>${button('Restaurer maintenant','confirm-restore','primary')}`);$('#dialog [data-action=confirm-restore]').onclick=async()=>{try{const {db}=await import('./store.js');const database=await db();await new Promise((ok,no)=>{const t=database.transaction(['state','captures','drafts'],'readwrite');t.objectStore('state').put(backup.state,'main');t.objectStore('captures').clear();captures.forEach(c=>t.objectStore('captures').put(c));t.objectStore('drafts').clear();backup.drafts.forEach(d=>t.objectStore('drafts').put(d));t.oncomplete=ok;t.onerror=()=>no(t.error);});state=backup.state;draft=backup.drafts[0]||null;$('#dialog').close();await render();toast('Sauvegarde restaurée.');}catch(e){toast(e.message);}};}
async function action(e){const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;try{if(analysisRunning){toast('Lecture en cours ; patiente avant de modifier le brouillon.');return;}
if(a==='add-stat'||a==='add-item'||a==='remove-detail'){const editor=el.closest('[data-detail-editor]');if(a==='add-stat')editor.querySelector('[data-stat-list]').insertAdjacentHTML('beforeend',statRow());if(a==='add-item')editor.querySelector(`[data-item-list="${el.dataset.module}"]`).insertAdjacentHTML('beforeend',itemRow(el.dataset.module));if(a==='remove-detail')el.closest('.detail-row').remove();if(el.closest('#record-form')||editor.closest('#record-form'))await saveDraft();return;}
if(a==='analyze-captures'){await analyzeCaptures(el);return;}
if(a==='view-details'){const r=state.records.find(r=>r.id===el.dataset.id);if(!r)throw new Error('Relevé inconnu');dialog('Fiche du '+recordLabel(r),detailView(r.details||emptyDetails())+(mayEdit(user,r.playerId)?button('Corriger cette fiche','edit-details','primary',`data-id="${esc(r.id)}"`):''));return;}
if(a==='edit-details'){const r=state.records.find(r=>r.id===el.dataset.id);if(!r||!mayEdit(user,r.playerId))throw new Error('Fiche non autorisée');const expected=structuredClone(r.details||null);dialog('Compléter la fiche du '+recordLabel(r),`<form id="details-form" class="stack">${detailEditor(r.details||emptyDetails())}<label class="field">Motif de correction<input name="reason" required maxlength="300" placeholder="Ex. ajout de la monture et des gemmes"></label><button type="submit" class="primary">Enregistrer les corrections</button></form>`);$('#details-form').onsubmit=async event=>{event.preventDefault();const form=event.target,b=form.querySelector('[type=submit]');b.disabled=true;try{const details=readDetails(form),reason=new FormData(form).get('reason');if(remote){await api('/api/records/details',{method:'POST',body:JSON.stringify({id:r.id,expected,details,reason})});await refresh();}else{r.details=details;audit('Fiche complétée : '+r.playerId+' · '+reason);await persist();}$('#dialog').close();await render();toast('Fiche complète enregistrée.');}catch(err){toast(err.message);}finally{b.disabled=false;}};return;}
if(['players','compare','home'].includes(a))go(a);if(a==='profile')go('player/'+encodeURIComponent(el.dataset.id));if(a==='import'){if(el.dataset.player){draft={...(draft||{id:crypto.randomUUID(),captureIds:[]}),playerId:el.dataset.player};await write('drafts',draft);}go('import');}if(a==='drive-connect'){if(!drive.client){drive.status('connecting','Chargement de la connexion Google…');await drive.prepare();toast('Google est prêt. Clique à nouveau sur Connecter Google Drive.');}else drive.connect();}
if(a==='refresh-membership'){await refresh();await render();}
if(a==='review-claim'){el.disabled=true;try{await api('/api/claims/review',{method:'POST',body:JSON.stringify({discordId:el.dataset.id,requestId:el.dataset.request,decision:el.dataset.decision})});await refresh();await render();toast('Demande traitée.');}finally{el.disabled=false;}}
if(a==='edit-record'){
 const record=state.records.find(r=>r.id===$('#admin-record')?.value);if(!record)throw new Error('Relevé inconnu');
 formDialog('Corriger le relevé du '+recordLabel(record),powerFields(String(record.power),'')+input('Niveau','level','number',`min="0" max="1000000" step="1" value="${record.level}"`)+input('Aventure','adventure','number',`min="0" max="1000000" step="1" value="${record.adventure}"`)+input('Motif de correction','reason','text','maxlength="300"'),async d=>{const values={power:power(d.power,d.powerUnit),level:Number(d.level),adventure:Number(d.adventure)};validateRecord({...record,...values});await adminMutation('edit-record',{id:record.id,...values,reason:d.reason,expected:{power:record.power,level:record.level,adventure:record.adventure}});});
}
if(a==='edit-account'){
 const account=accounts.find(x=>x.id===el.dataset.id);if(!account||account.protected)throw new Error('Compte protégé ou inconnu');
 formDialog('Droits de '+account.name,`<p>La modification s’applique aux prochaines actions du membre, y compris dans sa session actuelle.</p><label class="field">Rôle<select name="role">${['member','officer','admin'].map(r=>`<option value="${r}" ${r===account.role?'selected':''}>${roleLabel(r)}</option>`).join('')}</select></label><p class="stat-caption">Officier : gestion de la guilde et validation des inscriptions. Administrateur : peut aussi gérer les accès.</p><label class="field">Accès au site<select name="disabled"><option value="false" ${!account.disabled?'selected':''}>Actif</option><option value="true" ${account.disabled?'selected':''}>Désactivé</option></select></label><p>La désactivation conserve les données et bloque l’accès au site.</p>`,d=>adminMutation('account',{discordId:account.id,role:d.role,disabled:d.disabled==='true',expectedRole:account.role,expectedDisabled:account.disabled}));
}
if(['edit-player','edit-mode','edit-event'].includes(a)){
 const kind=a.slice(5),items=state[{player:'players',mode:'modes',event:'events'}[kind]],item=items.find(x=>x.id===el.dataset.id);if(!item)throw new Error('Élément inconnu');
 const fields=kind==='event'?input('Nom de l’événement','title','text',`maxlength="120" value="${esc(item.title)}"`)+input('Date','date','date',`value="${esc(item.date)}"`)+`<label class="field">Consignes<textarea name="description" required maxlength="3000">${esc(item.description)}</textarea></label>`:input(kind==='player'?'Pseudo dans le jeu':'Nom du mode','name','text',`maxlength="80" value="${esc(item.name)}"`);
 formDialog('Modifier '+(item.name||item.title),fields,d=>adminMutation(a,{id:item.id,...d}));
}
if(a==='seed-roster'){await adminMutation('seed-roster',{});await render();}
if(a==='drive-save')await drive.save();
if(a==='drive-disconnect'){drive.disconnect();toast('Drive déconnecté.');}
if(a==='drive-list'){driveFiles=await drive.list();dialog('Versions sauvegardées sur Drive',driveFiles.length?'<p>Choisis une version à restaurer sur cet appareil. Une confirmation te sera demandée.</p><div class="stack">'+driveFiles.map(f=>button(esc(new Date(f.createdTime).toLocaleString('fr-FR'))+' · '+Math.round(Number(f.size||0)/1024)+' Ko','drive-restore','quiet',`data-id="${esc(f.id)}"`)).join('')+'</div>':'<p>Aucune sauvegarde AlphaBet dans ce compte Google.</p>');}
if(a==='drive-restore'){if(!driveFiles.some(f=>f.id===el.dataset.id))throw new Error('Sauvegarde inconnue.');const file=await drive.download(el.dataset.id);$('#dialog').close();await restoreFile(file);}
if(a==='close')$('#dialog').close();if(a==='account')await login();if(a==='logout'){await api('/auth/logout',{method:'POST',body:'{}'});sessionStorage.removeItem('alphabet-session');user=null;state={schema:1,players:[],records:[],daily:[],modes:[],events:[],audit:[]};$('#dialog').close();await render();}if(a==='add-player')formDialog('Ajouter un joueur',input('Pseudo exact dans le jeu','name','text','maxlength="80"'),d=>adminMutation('player',d));if(a==='add-mode')formDialog('Ajouter un mode quotidien',input('Nom exact du mode','name','text','maxlength="80"'),d=>adminMutation('mode',d));if(a==='add-event')formDialog('Créer un événement',input('Nom de l’événement','title','text','maxlength="120"')+input('Date','date','date')+'<label class="field">Consignes<textarea name="description" required maxlength="3000"></textarea></label>',d=>adminMutation('event',d));if(a==='pair')formDialog('Apparier un compte',input('Identifiant Discord (numérique)','discordId','text','pattern="[0-9]{17,20}"')+`<label class="field">Joueur<select name="playerId"><option value="">Non apparié</option>${state.players.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><label class="field">Rôle<select name="role"><option value="member">Membre</option><option value="officer">Officier</option><option value="admin">Administrateur</option></select></label>`,d=>adminMutation('pair',d));if(a==='discard-draft'){if(draft)await remove('drafts',draft.id);draft=null;await render();toast('Brouillon abandonné.');}if(a==='export')await exportBackup();if(a==='restore'){const f=document.createElement('input');f.type='file';f.accept='.json,application/json';f.onchange=()=>f.files[0]&&restoreFile(f.files[0]).catch(e=>toast(e.message));f.click();}if(a==='view-captures'){const record=state.records.find(r=>r.id===el.dataset.id);const images=[];for(const id of record.captureIds||[]){if(remote){const {url}=await api('/api/captures/'+encodeURIComponent(id));images.push(`<a href="${esc(url)}" target="_blank" rel="noopener">Ouvrir la capture</a>`);}else{const c=await read('captures',id);if(c){const url=URL.createObjectURL(c.blob);previewURLs.push(url);images.push(`<img src="${url}" alt="${esc(c.name)}" style="max-width:100%;border-radius:10px">`);}}}dialog('Captures du relevé',images.join('')||'<p>Aucune capture disponible.</p>');}}catch(error){toast(error.message);}}
document.addEventListener('click',action);
document.addEventListener('input',e=>{if(e.target.id==='search'){filter=e.target.value;const pos=e.target.selectionStart;render().then(()=>{$('#search').focus();$('#search').setSelectionRange(pos,pos);});}if(e.target.closest('#record-form')&&e.target.type!=='file'){saveDraft().catch(error=>toast('Échec de sauvegarde : '+error.message));}});
document.addEventListener('change',async e=>{try{if(e.target.id==='sort'){sort=e.target.value;await render();}if(e.target.id==='week'&&e.target.value){currentWeek=weekOf(e.target.value);await render();}if(e.target.dataset.compare){const id=e.target.dataset.compare;if(e.target.checked&&selected.size>=5){e.target.checked=false;toast('Le comparateur accepte cinq joueurs maximum.');return;}e.target.checked?selected.add(id):selected.delete(id);await render();}if(e.target.dataset.mode){const p=currentPlayer();if(!mayEdit(user,p?.id))throw new Error('Profil non autorisé');const value={playerId:p.id,date:today(),modeId:e.target.dataset.mode,done:e.target.checked};if(remote){await api('/api/daily',{method:'POST',body:JSON.stringify(value)});await refresh();toast('Activité synchronisée');}else{state.daily=state.daily.filter(d=>!(d.playerId===p.id&&d.modeId===value.modeId&&d.date===value.date));state.daily.push(value);await persist();}}if(e.target.id==='captures'){clearTimeout(saveTimer);await saveDraft();const files=[...e.target.files];if(files.length+(draft.captureIds?.length||0)>MAX_CAPTURES)throw new Error(`Maximum ${MAX_CAPTURES} captures par relevé.`);for(const file of files)if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('Utilise des images PNG, JPEG ou WebP de 8 Mo maximum.');for(const file of files){const bitmap=await createImageBitmap(file);bitmap.close();const id=crypto.randomUUID();await write('captures',{id,name:file.name,blob:file});draft.captureIds.push(id);await write('drafts',draft);$('#draft-status').textContent=`${draft.captureIds.length} capture(s) conservée(s) dans le brouillon…`;}await write('drafts',draft);driveChanged();await previews();$('#draft-status').textContent='Captures sauvegardées sur cet appareil.';e.target.value='';}}catch(error){toast(error.message);}});
document.addEventListener('submit',async e=>{if(e.target.id==='claim-form'){e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{const playerId=new FormData(e.target).get('playerId');await api('/api/claim',{method:'POST',body:JSON.stringify({playerId})});await refresh();await render();toast('Demande envoyée au responsable.');}catch(error){toast(error.message);}finally{b.disabled=false;}return;}if(e.target.id!=='record-form')return;e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;clearTimeout(saveTimer);try{await saveDraft();const r=validateRecord({id:draft.id,playerId:draft.playerId,date:draft.date,time:draft.time,power:power(draft.power,draft.powerUnit),level:Number(draft.level),adventure:Number(draft.adventure),captureIds:draft.captureIds||[],details:validateDetails(draft.details||emptyDetails())});if(!mayEdit(user,r.playerId))throw new Error('Tu ne peux pas modifier cette fiche.');if(!remote&&state.records.some(x=>recordKey(x)===recordKey(r)))throw new Error('Un relevé existe déjà à cette date et cette heure. Choisis l’heure réelle du nouveau relevé.');if(remote){$('#draft-status').textContent='Envoi en cours… Le brouillon reste sur cet appareil jusqu’à confirmation.';const ids=[];for(const id of r.captureIds){$('#draft-status').textContent=`Envoi de la capture ${ids.length+1}/${r.captureIds.length}…`;const c=await read('captures',id);const data=await new Promise(ok=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.readAsDataURL(c.blob);});const result=await api('/api/captures',{method:'POST',body:JSON.stringify({id,playerId:r.playerId,name:c.name,data})});ids.push(result.id);}await api('/api/records',{method:'POST',body:JSON.stringify({...r,captureIds:ids})});await refresh();await remove('drafts',draft.id);}else{const next=structuredClone(state);next.records.push(r);next.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),actor:'Atelier local',action:`Relevé validé : ${state.players.find(p=>p.id===r.playerId)?.name} · ${recordLabel(r)}`});await commitRecord(next,draft,r);state=next;driveChanged();}draft=null;toast(remote?'Relevé synchronisé dans Google.':'Relevé validé et enregistré sur cet appareil.');go('player/'+encodeURIComponent(r.playerId));}catch(error){const status=$('#draft-status');if(status)status.textContent=remote?'Envoi non confirmé. Ton brouillon est conservé ; tu peux réessayer.':'Validation non confirmée. Ton brouillon reste disponible.';toast(error.message);}finally{b.disabled=false;}});
window.addEventListener('online',()=>{if(!remote&&drive.enabled)drive.save().catch(()=>{});});
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render().catch(e=>toast(e.message));});
async function start(){if(!remote){try{drive.token=JSON.parse(sessionStorage.getItem('alphabet-drive-token')||'null');driveStatus.last=JSON.parse(localStorage.getItem('alphabet-drive-last')||'null');if(driveStatus.last)driveStatus.text='Dernière copie Drive : '+new Date(driveStatus.last.at).toLocaleString('fr-FR')+' · connexion à vérifier';}catch{drive.token=null;}}
if(remote){state={schema:1,players:[],records:[],modes:[],daily:[],events:[],audit:[]};const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('ticket')){const ticket=hash.get('ticket'),verifier=sessionStorage.getItem('alphabet-verifier');history.replaceState(null,'',location.pathname);route='home';const r=await api('/auth/exchange',{method:'POST',body:JSON.stringify({ticket,verifier})});sessionStorage.setItem('alphabet-session',r.token);sessionStorage.removeItem('alphabet-verifier');}if(sessionStorage.getItem('alphabet-session')){try{await refresh();}catch(e){sessionStorage.removeItem('alphabet-session');toast(e.message);}}}else{state=await getState();user={name:'Atelier local',role:'officer',playerId:state.players.find(p=>p.id==='psykokwak')?.id||state.players[0]?.id};}const drafts=await all('drafts');draft=drafts.find(d=>!remote||d.playerId===user?.playerId)||null;await render();if(!remote)drive.prepare().then(()=>{if(drive.connected()){drive.enabled=true;drive.changed();}}).catch(error=>drive.status('error',error.message));if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>toast('Le mode hors ligne n’a pas pu être activé.'));}}
start().catch(error=>{$('#app').innerHTML=`<main><h1>AlphaBet ne peut pas démarrer</h1><p>${esc(error.message)}</p><p>Ouvre le site via son adresse HTTP/HTTPS et autorise le stockage du navigateur.</p></main>`;});
